name: 04-actions-workflow

on: push

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: stepup Node
        uses: actions/checkout@v3
        with:
            node version: '18'
      -run: npm install
      -run: npm test      